const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '..', 'controllers', 'voiceController.js');
const fileLines = fs.readFileSync(targetPath, 'utf8').split('\n');

// Lines 1 to 973 are valid helper functions (up to callGeminiIfAvailable)
const part1 = fileLines.slice(0, 973).join('\n');

const part2 = [
'// ── Dynamic Anti-Repetition Phrasing Templates ────────────────',
'const QUESTION_TEMPLATES = {',
'    occupation: {',
'        en: [',
'            "To find the most suitable schemes, **what is your current occupation or area of interest?**\\n*(e.g., 🌾 Farmer, 🎓 Student, 💼 Business/Shopkeeper, 👩 Women Welfare, 🏥 Healthcare)*",',
'            "I can personalize your scheme recommendations! **Which category describes you best?**\\n*(e.g., Farmer, Student, Self-Employed/Business, Homemaker, or Job Seeker)*",',
'            "Could you tell me **what type of assistance or occupation you\'re inquiring for?**\\n*(Options: Agriculture, Scholarship, Business Loan, Housing, or Healthcare)*"',
'        ],',
'        hi: [',
'            "आपके लिए सबसे सही सरकारी योजनाएं खोजने के लिए, **आपका व्यवसाय या मुख्य आवश्यकता क्या है?**\\n*(जैसे: 🌾 किसान, 🎓 छात्र, 💼 व्यवसाय/दुकानदार, 👩 महिला कल्याण, 🏥 स्वास्थ्य)*",',
'            "मैं आपको सटीक योजनाएं बता सकता हूँ। **कृपया बताएं आपकी श्रेणी कौन सी है?**\\n*(जैसे: किसान, विद्यार्थी, स्वरोजगार/व्यवसाय, गृहिणी, या नौकरी खोजकर्ता)*"',
'        ],',
'        gu: [',
'            "તમારા માટે સૌથી યોગ્ય સરકારી યોજનાઓ શોધવા માટે, **તમારો હાલનો વ્યવસાય કે જરૂરિયાત શું છે?**\\n*(દા.ત., 🌾 ખેડૂત, 🎓 વિદ્યાર્થી, 💼 વેપારી/દુકાનદાર, 👩 મહિલા કલ્યાણ, 🏥 આરોગ્ય)*",',
'            "હું તમને સંબંધિત યોજનાઓ બતાવી શકું છું! **તમારી કેટેગરી કઈ છે?**\\n*(દા.ત., ખેડૂત, વિદ્યાર્થી, ધંધાદારી/વેપારી, ગૃહિણી, કે નોકરી શોધનાર)*"',
'        ]',
'    },',
'    state: {',
'        en: [',
'            "Great! **Which state or Union Territory do you currently reside in?**\\n*(e.g., Gujarat, Maharashtra, Rajasthan, Uttar Pradesh, Delhi)*",',
'            "To check state-specific benefits, **could you share your home state or city?**"',
'        ],',
'        hi: [',
'            "बहुत बढ़िया! **आप भारत के किस राज्य या केंद्र शासित प्रदेश में रहते हैं?**\\n*(जैसे: गुजरात, महाराष्ट्र, राजस्थान, उत्तर प्रदेश, दिल्ली)*",',
'            "राज्य सरकार की विशेष योजनाएं देखने के लिए, **कृपया अपना राज्य या शहर बताएं?**"',
'        ],',
'        gu: [',
'            "સરસ! **તમે કયા રાજ્યમાં અથવા કયા શહેરમાં રહો છો?**\\n*(દા.ત., ગુજરાત, મહારાષ્ટ્ર, રાજસ્થાન, અમદાવાદ, સુરત)*",',
'            "રાજ્ય સરકારની વિશેષ સહાય ચકાસવા માટે, **તમારું રાજ્ય જણાવશો?**"',
'        ]',
'    },',
'    income: {',
'        en: [',
'            "Almost done! **What is your approximate annual household income?**\\n*(e.g., Below ₹1 Lakh, ₹1-2.5 Lakh, ₹2.5-5 Lakh, or Above ₹5 Lakh)*",',
'            "To confirm financial eligibility thresholds, **could you share your yearly family income range?**"',
'        ],',
'        hi: [',
'            "अंतिम जानकारी! **आपकी अनुमानित वार्षिक पारिवारिक आय कितनी है?**\\n*(जैसे: 1 लाख से कम, 1 से 2.5 लाख, 2.5 से 5 लाख, या 5 लाख से अधिक)*",',
'            "वित्तीय पात्रता जांचने के लिए, **कृपया अपनी वार्षिक आय सीमा बताएं?**"',
'        ],',
'        gu: [',
'            "છેલ્લી વિગત! **તમારી અંદાજિત વાર્ષિક કૌટુંબિક આવક કેટલી છે?**\\n*(દા.ત., ૧ લાખથી ઓછી, ૧ થી ૨.૫ લાખ, ૨.૫ થી ૫ લાખ, કે ૫ લાખથી વધુ)*",',
'            "આર્થિક પાત્રતા ચકાસવા માટે, **તમારી અંદાજે વાર્ષિક આવક જણાવશો?**"',
'        ]',
'    },',
'    greetings: {',
'        en: [',
'            "🙏 **Namaste! Welcome to JanSahay AI.**\\n\\nI am your AI assistant for Indian government schemes. I can help you find schemes you are eligible for, check eligibility, and guide you on how to apply in English, Hindi, or Gujarati.\\n\\nHow can I help you today?",',
'            "🙏 **Hello! Welcome to JanSahay AI.**\\n\\nI can help you explore Central and State government schemes. What would you like to know today?"',
'        ],',
'        hi: [',
'            "🙏 **नमस्ते! JanSahay AI में आपका स्वागत है।**\\n\\nमैं भारत सरकार की योजनाओं के लिए आपका AI सहायक हूँ। मैं आपको छात्रवृत्ति, किसान योजनाएं, स्वास्थ्य और व्यवसाय ऋण खोजने में मदद कर सकता हूँ।\\n\\nआज आप क्या जानना चाहेंगे?",',
'            "🙏 **प्रणाम! JanSahay AI में आपका स्वागत है।**\\n\\nआप मुझसे हिंदी, अंग्रेजी या गुजराती में सरकारी योजनाओं के बारे में पूछ सकते हैं। बताएं मैं आपकी क्या मदद करूँ?"',
'        ],',
'        gu: [',
'            "🙏 **નમસ્તે! JanSahay AI માં આપનું સ્વાગત છે.**\\n\\nહું ભારત સરકાર અને ગુજરાત સરકારની યોજનાઓ માટે તમારો AI સહાયક છું. હું તમને ખેતી, શિક્ષણ, આરોગ્ય અને બિઝનેસ લોનની યોજનાઓ શોધવામાં મદદ કરી શકું છું.\\n\\nઆજે તમે શું જાણવા માગો છો?",',
'            "🙏 **નમસ્તે! JanSahay AI માં આપનું હાર્દિક સ્વાગત છે.**\\n\\nતમે મને ગુજરાતી, હિન્દી કે અંગ્રેજીમાં સરકારી યોજનાઓ વિશે પૂછી શકો છો. હું તમને કેવી રીતે મદદ કરી શકું?"',
'        ]',
'    }',
'};',
'',
'function pickTemplate(key, lang = \'en\', attempt = 1) {',
'    const group = QUESTION_TEMPLATES[key] || QUESTION_TEMPLATES.occupation;',
'    const list = group[lang] || group.en || [];',
'    if (!list.length) return \'\';',
'    const idx = (attempt - 1) % list.length;',
'    return list[idx];',
'}',
'',
'// ── Format Matched Schemes List ───────────────────────────────',
'function formatMatchedSchemes(matchedSchemes, profile, lang = \'en\', page = 0) {',
'    if (!matchedSchemes || matchedSchemes.length === 0) {',
'        if (lang === \'gu\') {',
'            return {',
'                reply: "માફ કરશો, તમારી વિગતો સાથે મેળ ખાતી કોઈ યોજના મળી નથી. કૃપા કરીને અન્ય કેટેગરી અથવા કીવર્ડ સાથે પ્રયાસ કરો.",',
'                spoken: "માફ કરશો, તમારી વિગતો સાથે મેળ ખાતી કોઈ યોજના મળી નથી."',
'            };',
'        }',
'        if (lang === \'hi\') {',
'            return {',
'                reply: "क्षमा करें, आपके विवरण से मेल खाने वाली कोई योजना नहीं मिली। कृपया अन्य श्रेणी या कीवर्ड के साथ प्रयास करें।",',
'                spoken: "क्षमा करें, आपके विवरण से मेल खाने वाली कोई योजना नहीं मिली."',
'            };',
'        }',
'        return {',
'            reply: "Sorry, no schemes found matching your profile. Please try asking with different keywords or category.",',
'            spoken: "Sorry, no schemes found matching your profile."',
'        };',
'    }',
'',
'    if (lang === \'gu\') {',
'        const listText = matchedSchemes.map((s, idx) => {',
'            const num = (page * 4) + idx + 1;',
'            return "### " + num + ". **" + s.title + "**\\n- **લાભ:** " + s.benefits + "\\n- **પાત્રતા:** આપેલી માહિતી મુજબ, તમે પાત્ર હોઈ શકો છો.\\n- 🔗 [સત્તાવાર પોર્ટલ પર અરજી કરો](" + (s.applyLink || "https://www.myscheme.gov.in/") + ")";',
'        }).join(\'\\n\\n---\\n\\n\');',
'',
'        const reply = "🔍 **તમારા માટે ઉપલબ્ધ સરકારી યોજનાઓ:**\\n\\n" + listText + "\\n\\n💡 *વધુ માહિતી માટે કહો: \\"1લી યોજના વિશે જણાવો\\" અથવા \\"અરજી કેવી રીતે કરવી?\\"*";',
'        const spoken = "તમારા માટે યોજનાઓ મળી છે, જેમાં " + matchedSchemes.map(s => s.title).join(\', \') + " શામેલ છે. વધુ વિગતો માટે કોઈપણ યોજનાનું નામ કહો.";',
'        return { reply, spoken };',
'    }',
'',
'    if (lang === \'hi\') {',
'        const listText = matchedSchemes.map((s, idx) => {',
'            const num = (page * 4) + idx + 1;',
'            return "### " + num + ". **" + s.title + "**\\n- **लाभ:** " + s.benefits + "\\n- **पात्रता:** दी गई जानकारी के आधार पर, आप पात्र हो सकते हैं।\\n- 🔗 [आधिकारिक पोर्टल पर आवेदन करें](" + (s.applyLink || "https://www.myscheme.gov.in/") + ")";',
'        }).join(\'\\n\\n---\\n\\n\');',
'',
'        const reply = "🔍 **सत्यापित सरकारी योजनाएं:**\\n\\n" + listText + "\\n\\n💡 *अधिक जानकारी के लिए कहें: \\"पहली योजना के बारे में बताएं\\" या \\"आवेदन कैसे करें?\\"*";',
'        const spoken = "आपके लिए योजनाएं मिली हैं, जैसे " + matchedSchemes.map(s => s.title).join(\', \') + ". अधिक जानकारी के लिए किसी भी योजना का नाम बताएं.";',
'        return { reply, spoken };',
'    }',
'',
'    const listText = matchedSchemes.map((s, idx) => {',
'        const num = (page * 4) + idx + 1;',
'        return "### " + num + ". **" + s.title + "**\\n- **Benefits:** " + s.benefits + "\\n- **Eligibility:** Based on the information provided, you may be eligible.\\n- 🔗 [Apply on Official Portal](" + (s.applyLink || "https://www.myscheme.gov.in/") + ")";',
'    }).join(\'\\n\\n---\\n\\n\');',
'',
'    const reply = "🔍 **Government Schemes Matching Your Profile:**\\n\\n" + listText + "\\n\\n💡 *Ask: \\"Tell me about scheme 1\\", \\"What documents are required?\\", or \\"How do I apply?\\"*";',
'    const spoken = "I found matching schemes including " + matchedSchemes.map(s => s.title).join(\', \') + ". Mention any scheme to hear full details or how to apply.";',
'    return { reply, spoken };',
'}',
'',
'// ── Main Voice Assistant Chat Handler ─────────────────────────',
'exports.chat = async (req, res) => {',
'    try {',
'        const userText = (req.body.query || req.body.message || \'\').trim();',
'        const preferredLang = req.body.language;',
'        const sessionId = req.body.sessionId;',
'',
'        if (!userText) {',
'            return res.status(400).json({',
'                success: false,',
'                error: \'Query or message text is required\'',
'            });',
'        }',
'',
'        const session = getOrCreateSession(sessionId);',
'        const lang = detectLanguage(userText, preferredLang);',
'        const lower = userText.toLowerCase();',
'',
'        // Helper to format consistent response JSON',
'        function respond(reply, spokenText, state = \'idle\', matchedSchemes = []) {',
'            session.history.push({ role: \'user\', content: userText, timestamp: Date.now() });',
'            session.history.push({ role: \'assistant\', content: reply, timestamp: Date.now() });',
'',
'            return res.json({',
'                success: true,',
'                reply,',
'                spokenText: spokenText || createSpokenText(reply),',
'                language: lang,',
'                state,',
'                schemes: matchedSchemes.map(s => ({',
'                    id: s.id,',
'                    title: s.title,',
'                    category: s.category,',
'                    state: s.state,',
'                    benefits: s.benefits,',
'                    applyLink: s.applyLink,',
'                    matchScore: s.matchScore || \'95%\'',
'                })),',
'                sessionId: session.id,',
'                profile: session.profile',
'            });',
'        }',
'',
'        // 1. Security Check: Reject OTP / PIN / Passwords',
'        if (checkSecuritySensitive(userText)) {',
'            let securityReply = \'\';',
'            let spokenSec = \'\';',
'            if (lang === \'gu\') {',
'                securityReply = \'🔒 **સુરક્ષા ચેતવણી:** તમારી સુરક્ષા માટે, કૃપા કરીને ક્યારેય તમારો **OTP**, **UPI PIN**, **ATM PIN**, અથવા **બેંક પાસવર્ડ** શેર કરશો નહીં. જનસહાય AI ક્યારેય તમારી ગુપ્ત વિગતો માંગશે નહીં.\';',
'                spokenSec = \'તમારી સુરક્ષા માટે, કૃપા કરીને તમારો ઓટીપી કે યુપીઆઈ પિન કોઈની સાથે શેર કરશો નહીં.\';',
'            } else if (lang === \'hi\') {',
'                securityReply = \'🔒 **सुरक्षा चेतावनी:** आपकी सुरक्षा के लिए, कृपया कभी भी अपना **OTP**, **UPI PIN**, **ATM PIN**, या **बैंक पासवर्ड** साझा न करें। जनसहाय एआई (JanSahay AI) कभी भी आपसे गोपनीय क्रेडेंशियल नहीं मांगता है।\';',
'                spokenSec = \'आपकी सुरक्षा के लिए, कृपया कभी भी अपना ओटीपी, यूपीआई पिन या बैंक पासवर्ड साझा न करें.\';',
'            } else {',
'                securityReply = \'🔒 **Security Alert:** For your safety, please never share your **OTP**, **UPI PIN**, **ATM PIN**, or **bank passwords**. JanSahay AI will never ask for your confidential authentication credentials.\';',
'                spokenSec = \'For your safety, please never share your OTP, UPI PIN, ATM PIN, or banking passwords. JanSahay AI will never ask for them.\';',
'            }',
'            return respond(securityReply, spokenSec, \'security\');',
'        }',
'',
'        // 2. Greetings Handling (Checked early so greetings like "Hello JanSahay" respond with welcome)',
'        const isGreeting = /^(hi|hello|hey|namaste|kem cho|kaisa hai|kaise ho|start|help|pranam|namaskar)(\\s+(jansahay|assistant|ai|bot|ji|sir|madam))?[\\s!.]*$/i.test(lower) ||',
'                           /^(hello|hi|hey|namaste)\\s+jansahay/i.test(lower) ||',
'                           /^નમસ્તે|^કેમ છો|^नमस्ते|^प्रणाम/.test(userText);',
'        if (isGreeting && session.history.length <= 3) {',
'            const greetText = pickTemplate(\'greetings\', lang, session.history.length + 1);',
'            const spokenGreet = createSpokenText(greetText);',
'            return respond(greetText, spokenGreet, \'idle\');',
'        }',
'',
'        // 3. Category Switch Detection & Profile Updates',
'        const explicitCategory = detectCategoryInText(userText);',
'        const previousCategory = session.profile.category_need;',
'        const isDirectSchemeRequest = /\\b(scheme|schemes|yojana|yojna|loan|loans|mudra|scholarship|scholarships|batao|dikhao|show|list|find|search|give|get|chahiye|joiye|what about)\\b/i.test(lower) ||',
'                                      /યોજના|સ્કીમ|લોન|શિષ્યવૃત્તિ|બતાવો|જોઈએ|યજના|योजना|स्कीम|लोन|छात्रवृत्ति|बताओ|दिखाओ|चाहिए/.test(userText);',
'',
'        if (explicitCategory && explicitCategory.key !== previousCategory) {',
'            console.log(`[JanSahay] Category switch detected: ${previousCategory} → ${explicitCategory.key}`);',
'            session.profile.category_need = explicitCategory.key;',
'            session.profile.occupation = explicitCategory.defaultOccupation;',
'            if (explicitCategory.gender) session.profile.gender = explicitCategory.gender;',
'            session.activeScheme = null;',
'            session.lastSchemes = [];',
'            session.schemePage = 0;',
'            if (session.pendingQuestion !== \'occupation\' || isDirectSchemeRequest) {',
'                session.pendingQuestion = null;',
'            }',
'        }',
'',
'        // Extract any other profile information (state, city, income, age, gender)',
'        session.profile = extractProfileDetails(userText, session.profile);',
'',
'        // 4. Intent & Targeted Scheme Resolution',
'        const isHowToApply = /\\b(how to apply|how do i apply|how can i apply|where to apply|where can i apply|application process|application procedure|application details|application form|application link|apply process|apply details|apply link|registration process|register|how to register|form bharvu|arji kevi rite|arji karvi|aavedan kaise|kaha aavedan|online apply|apply|application|aavedan|arji)\\b/i.test(lower) ||',
'                             /અરજી કેવી રીતે|અરજી ક્યાં|ફોર્મ કેવી રીતે|અરજીની વિગત|અરજી પ્રક્રિયા|આવેદન કૈસે|आवेदन कैसे|कहाँ आवेदन|आवेदन प्रक्रिया|आवेदन विवरण|फॉर्म कैसे भरें/.test(userText);',
'',
'        const isDocumentsQuery = /\\b(document|documents|required documents|documents needed|what documents|kagad|kagadiyo|dastavez|papers|proof|aadhaar)\\b/i.test(lower) ||',
'                                 /દસ્તાવેજ|કાગળો|પુરાવા|દસ્તાવેજો|દસ્તાવેજની યાદી|दस्तावेज|कागजात|कागज़/.test(userText);',
'',
'        const isEligibilityQuery = /\\b(eligible|eligibility|eligibility criteria|qualify|who can apply|who is eligible|patrata|kisko milega|mane malse|maru nam)\\b/i.test(lower) ||',
'                                   /પાત્રતા|લાયકાત|કોને મળે|કોણ પાત્ર|પાત્ર|पात्रता|किसे मिलेगा|कौन पात्र/.test(userText);',
'',
'        const isSchemeDetailQuery = /\\b(tell me about|more details|more info|details about|information about|explain|details of|vishe mahiti|vishe jankari|ke baare me|ke bare me)\\b/i.test(lower) ||',
'                                    /વિશે માહિતી|વિગત|જાણકારી|માહિતી આપો|કેવી છે|કેવો છે|કેવી યોજના|કેવી સ્કીમ|के बारे में|जानकारी|बताएं/.test(userText);',
'',
'        const isShowMore = /\\b(more schemes|other schemes|next schemes|show more|biji yojana|aur yojana|dusri yojana|batao aur|next page)\\b/i.test(lower) ||',
'                           /વધુ યોજના|અન્ય યોજના|और योजना|दूसरी योजना|अगली/.test(userText);',
'',
'        // Check if user is referencing a particular scheme (by ordinal: 1st, 2nd, scheme 2, or name/keyword)',
'        const targetedScheme = resolveTargetScheme(userText, session);',
'',
'        // 5. Targeted Scheme Follow-Up (Precise Scheme Requested)',
'        if (targetedScheme) {',
'            session.activeScheme = targetedScheme;',
'',
'            if (isHowToApply) {',
'                const appInfo = formatSchemeApplication(targetedScheme, lang);',
'                return respond(appInfo.reply, appInfo.spoken, \'info\', [targetedScheme]);',
'            }',
'',
'            if (isDocumentsQuery) {',
'                const docInfo = formatSchemeDocuments(targetedScheme, lang);',
'                return respond(docInfo.reply, docInfo.spokenText, \'info\', [targetedScheme]);',
'            }',
'',
'            if (isEligibilityQuery) {',
'                const eligInfo = formatSchemeEligibility(targetedScheme, lang);',
'                return respond(eligInfo.reply, eligInfo.spokenText, \'info\', [targetedScheme]);',
'            }',
'',
'            const explanation = formatSchemeExplanation(targetedScheme, lang);',
'            return respond(explanation.reply, explanation.spokenText, \'info\', [targetedScheme]);',
'        }',
'',
'        // 6. Active Scheme Context Follow-Up',
'        if (session.activeScheme && (isHowToApply || isDocumentsQuery || isEligibilityQuery || isSchemeDetailQuery) && !explicitCategory) {',
'            const activeScheme = session.activeScheme;',
'',
'            if (isHowToApply) {',
'                const appInfo = formatSchemeApplication(activeScheme, lang);',
'                return respond(appInfo.reply, appInfo.spoken, \'info\', [activeScheme]);',
'            }',
'',
'            if (isDocumentsQuery) {',
'                const docInfo = formatSchemeDocuments(activeScheme, lang);',
'                return respond(docInfo.reply, docInfo.spokenText, \'info\', [activeScheme]);',
'            }',
'',
'            if (isEligibilityQuery) {',
'                const eligInfo = formatSchemeEligibility(activeScheme, lang);',
'                return respond(eligInfo.reply, eligInfo.spokenText, \'info\', [activeScheme]);',
'            }',
'',
'            if (isSchemeDetailQuery) {',
'                const explanation = formatSchemeExplanation(activeScheme, lang);',
'                return respond(explanation.reply, explanation.spokenText, \'info\', [activeScheme]);',
'            }',
'        }',
'',
'        // 7. Pagination ("Show More Schemes")',
'        if (isShowMore) {',
'            session.schemePage = (session.schemePage || 0) + 1;',
'            const nextSchemes = matchSchemesWithIntelligence({',
'                query: userText,',
'                profile: session.profile,',
'                limit: 4,',
'                offset: session.schemePage * 4',
'            });',
'',
'            if (nextSchemes.length > 0) {',
'                session.lastSchemes = nextSchemes;',
'                session.activeScheme = nextSchemes[0];',
'                const formatted = formatMatchedSchemes(nextSchemes, session.profile, lang, session.schemePage);',
'                return respond(formatted.reply, formatted.spoken, \'matched\', nextSchemes);',
'            } else {',
'                session.schemePage = 0;',
'            }',
'        }',
'',
'        // 8. Gratitude Handling',
'        const isGratitude = /\\b(thank you|thanks|aabhar|dhanyawad|shukriya|thanku|thx|great thanks|ok thanks|okay thanks)\\b/i.test(lower) ||',
'                            /આભાર|ધન્યવાદ|શુક્રિયા|ધ્યાન રાખજો/.test(userText);',
'        if (isGratitude && !explicitCategory) {',
'            let reply = \'\';',
'            let spoken = \'\';',
'            if (lang === \'gu\') {',
'                reply = "🙏 **તમારો ખૂબ ખૂબ આભાર!**\\n\\nજો તમને અરજી કરવા, દસ્તાવેજો તૈયાર કરવા અથવા અન્ય કોઈ સરકારી યોજના વિશે પ્રશ્ન હોય, તો મને જરૂર પૂછો. હું તમારી સેવામાં હાજર છું!";',
'                spoken = "તમારો ખૂબ ખૂબ આભાર! જો તમને અરજી કે અન્ય કોઈ યોજના વિશે સવાલ હોય, તો જરૂર પૂછો.";',
'            } else if (lang === \'hi\') {',
'                reply = "🙏 **आपका बहुत-बहुत धन्यवाद!**\\n\\nयदि आपको आवेदन प्रक्रिया, आवश्यक दस्तावेजों या अन्य किसी सरकारी योजना के बारे में जानकारी चाहिए, तो बेझिझक पूछें।";',
'                spoken = "आपका बहुत धन्यवाद! यदि आपको आवेदन या किसी अन्य योजना की जानकारी चाहिए, तो जरूर पूछें.";',
'            } else {',
'                reply = "🙏 **You\'re very welcome!**\\n\\nIf you need step-by-step guidance on applying, document requirements, or discovering other government schemes, just let me know!";',
'                spoken = "You\'re very welcome! Let me know if you need help with applications, documents, or other schemes.";',
'            }',
'            return respond(reply, spoken, \'idle\');',
'        }',
'',
'        // 9. Specific Scheme by Title / Brand Name',
'        const specificKeywords = [',
'            \'pm-kisan\', \'pmkisan\', \'ayushman\', \'pmjay\', \'jan dhan\', \'pmjdy\',',
'            \'sukanya\', \'vishwakarma\', \'mysy\', \'vhali dikri\',',
'            \'maa amrutam\', \'surya ghar\', \'fasal bima\', \'pmfby\', \'e-drive\',',
'            \'fame\', \'mgnrega\', \'atal pension\', \'apy\', \'ujjwala\'',
'        ];',
'',
'        let matchedSpecificScheme = null;',
'        for (const kw of specificKeywords) {',
'            if (lower.includes(kw)) {',
'                matchedSpecificScheme = schemes.find(s =>',
'                    s.title.toLowerCase().includes(kw) ||',
'                    (s.tags && s.tags.some(t => t.toLowerCase().includes(kw)))',
'                );',
'                if (matchedSpecificScheme) break;',
'            }',
'        }',
'',
'        if (matchedSpecificScheme && !explicitCategory) {',
'            session.activeScheme = matchedSpecificScheme;',
'            session.lastSchemes = [matchedSpecificScheme];',
'            const explanation = formatSchemeExplanation(matchedSpecificScheme, lang);',
'            return respond(explanation.reply, explanation.spokenText, \'info\', [matchedSpecificScheme]);',
'        }',
'',
'        // 10. Intelligent Scheme Matching & Progressive Questionnaire',
'        const hasCategory = Boolean(session.profile.category_need || explicitCategory);',
'        const hasState = Boolean(session.profile.state);',
'        const hasIncome = Boolean(session.profile.income);',
'',
'        // Single-shot complete profile: match immediately',
'        if (hasCategory && hasState && hasIncome) {',
'            session.pendingQuestion = null;',
'            const matched = matchSchemesWithIntelligence({',
'                query: userText,',
'                profile: session.profile,',
'                limit: 4,',
'                offset: 0',
'            });',
'            if (matched.length > 0) {',
'                session.lastSchemes = matched;',
'                session.activeScheme = matched[0];',
'                session.schemePage = 0;',
'                const formatted = formatMatchedSchemes(matched, session.profile, lang, 0);',
'                return respond(formatted.reply, formatted.spoken, \'matched\', matched);',
'            }',
'        }',
'',
'        // A. Handle active onboarding questionnaire progression',
'        if (session.pendingQuestion) {',
'            if (session.pendingQuestion === \'occupation\') {',
'                if (hasCategory) {',
'                    session.pendingQuestion = \'state\';',
'                    session.questionAttempts[\'state\'] = (session.questionAttempts[\'state\'] || 0) + 1;',
'                    const questionText = pickTemplate(\'state\', lang, session.questionAttempts[\'state\']);',
'                    return respond(questionText, createSpokenText(questionText), \'asking\');',
'                } else {',
'                    session.questionAttempts[\'occupation\'] = (session.questionAttempts[\'occupation\'] || 0) + 1;',
'                    const questionText = pickTemplate(\'occupation\', lang, session.questionAttempts[\'occupation\']);',
'                    return respond(questionText, createSpokenText(questionText), \'asking\');',
'                }',
'            }',
'',
'            if (session.pendingQuestion === \'state\') {',
'                if (hasState) {',
'                    session.pendingQuestion = \'income\';',
'                    session.questionAttempts[\'income\'] = (session.questionAttempts[\'income\'] || 0) + 1;',
'                    const questionText = pickTemplate(\'income\', lang, session.questionAttempts[\'income\']);',
'                    return respond(questionText, createSpokenText(questionText), \'asking\');',
'                } else {',
'                    session.questionAttempts[\'state\'] = (session.questionAttempts[\'state\'] || 0) + 1;',
'                    if (session.questionAttempts[\'state\'] > 2) {',
'                        session.profile.state = \'All India\';',
'                        session.pendingQuestion = \'income\';',
'                        const questionText = pickTemplate(\'income\', lang, 1);',
'                        return respond(questionText, createSpokenText(questionText), \'asking\');',
'                    } else {',
'                        const questionText = pickTemplate(\'state\', lang, session.questionAttempts[\'state\']);',
'                        return respond(questionText, createSpokenText(questionText), \'asking\');',
'                    }',
'                }',
'            }',
'',
'            if (session.pendingQuestion === \'income\') {',
'                if (hasIncome || /skip|leave/i.test(lower) || (session.questionAttempts[\'income\'] || 0) >= 2) {',
'                    if (!hasIncome) session.profile.income = \'1l-2.5l\';',
'                    session.pendingQuestion = null;',
'                    const matched = matchSchemesWithIntelligence({',
'                        query: userText,',
'                        profile: session.profile,',
'                        limit: 4,',
'                        offset: 0',
'                    });',
'                    session.lastSchemes = matched;',
'                    session.activeScheme = matched[0];',
'                    session.schemePage = 0;',
'                    const formatted = formatMatchedSchemes(matched, session.profile, lang, 0);',
'                    return respond(formatted.reply, formatted.spoken, \'matched\', matched);',
'                } else {',
'                    session.questionAttempts[\'income\'] = (session.questionAttempts[\'income\'] || 0) + 1;',
'                    const questionText = pickTemplate(\'income\', lang, session.questionAttempts[\'income\']);',
'                    return respond(questionText, createSpokenText(questionText), \'asking\');',
'                }',
'            }',
'        }',
'',
'        // B. If user introduces category and state but no income, ask for income',
'        if (hasCategory && hasState && !hasIncome && !isDirectSchemeRequest) {',
'            session.pendingQuestion = \'income\';',
'            session.questionAttempts[\'income\'] = (session.questionAttempts[\'income\'] || 0) + 1;',
'            const questionText = pickTemplate(\'income\', lang, session.questionAttempts[\'income\']);',
'            return respond(questionText, createSpokenText(questionText), \'asking\');',
'        }',
'',
'        // C. General Scheme Discovery Onboarding Initiation',
'        const isSeekingSchemes =',
'            /\\b(scheme|schemes|yojana|yojna|help|apply|aid|support|batao|chahiye|joiye|find|karo|need government schemes|i need)\\b/i.test(lower) ||',
'            /યોજના|સ્કીમ|સહાય|મદદ|જોઈએ|યજના|स्कीम|चाहिए|सहायता/.test(userText);',
'',
'        if (isSeekingSchemes && !hasCategory) {',
'            session.pendingQuestion = \'occupation\';',
'            session.questionAttempts[\'occupation\'] = (session.questionAttempts[\'occupation\'] || 0) + 1;',
'            const questionText = pickTemplate(\'occupation\', lang, session.questionAttempts[\'occupation\']);',
'            return respond(questionText, createSpokenText(questionText), \'asking\');',
'        }',
'',
'        // D. Direct Category Search or Topic Switch',
'        if (explicitCategory || (hasCategory && hasState)) {',
'            session.pendingQuestion = null;',
'            const matched = matchSchemesWithIntelligence({',
'                query: userText,',
'                profile: session.profile,',
'                limit: 4,',
'                offset: 0',
'            });',
'',
'            if (matched.length > 0) {',
'                session.lastSchemes = matched;',
'                session.activeScheme = matched[0];',
'                session.schemePage = 0;',
'                const formatted = formatMatchedSchemes(matched, session.profile, lang, 0);',
'                return respond(formatted.reply, formatted.spoken, \'matched\', matched);',
'            }',
'        }',
'',
'        // 11. General Platform Inquiries',
'        if (/\\b(what is jansahay|about jansahay|how does it work|kaise kaam karta hai|jansahay shu chhe|who are you|kon ho|tamne kon chho|free hai|free chhe)\\b/i.test(lower)) {',
'            let reply = \'\';',
'            let spokenText = \'\';',
'',
'            if (lang === \'gu\') {',
'                reply = "🤖 **જનસહાય AI વિશે:**\\n\\n" +',
'                        "જનસહાય AI એ ભારત સરકાર અને રાજ્ય સરકારોની 4,700+ કલ્યાણકારી યોજનાઓ શોધવા માટેનું એક વિશ્વસનીય પ્લેટફોર્મ છે.\\n\\n" +',
'                        "✨ **અમે કેવી રીતે મદદ કરીએ છીએ:**\\n" +',
'                        "- તમારી પ્રોફાઇલ મુજબ યોગ્ય યોજનાઓની ભલામણ\\n" +',
'                        "- લાભો, પાત્રતા અને જરૂરી દસ્તાવેજોની સરળ સમજૂતી\\n" +',
'                        "- સત્તાવાર અરજી લિંક સુધી સીધું માર્ગદર્શન\\n\\n" +',
'                        "તમે ગુજરાતી, હિન્દી કે અંગ્રેજીમાં કોઈપણ સરકારી યોજના વિશે પૂછી શકો છો!";',
'                spokenText = "જનસહાય AI ભારત સરકાર અને રાજ્ય સરકારોની યોજનાઓ શોધવાનું વિશ્વસનીય પ્લેટફોર્મ છે. તમે ગુજરાતી, હિન્દી અથવા અંગ્રેજીમાં કોઈપણ સરકારી યોજના વિશે પૂછી શકો છો.";',
'            } else if (lang === \'hi\') {',
'                reply = "🤖 **जनसहाय एआई (JanSahay AI) के बारे में:**\\n\\n" +',
'                        "जनसहाय एआई भारत सरकार और राज्य सरकारों की 4,700 से अधिक कल्याणकारी योजनाओं को खोजने का एक आधिकारिक एआई सहायक है।\\n\\n" +',
'                        "✨ **हमारी विशेषताएं:**\\n" +',
'                        "- आपकी प्रोफ़ाइल के अनुसार सटीक योजनाओं की सिफारिश\\n" +',
'                        "- पात्रता, लाभ और आवश्यक दस्तावेजों की विस्तृत जानकारी\\n" +',
'                        "- आधिकारिक आवेदन पोर्टल का सीधा लिंक\\n\\n" +',
'                        "आप हिंदी, गुजराती या अंग्रेजी में अपनी आवश्यकतानुसार कोई भी योजना पूछ सकते हैं!";',
'                spokenText = "जनसहाय एआई भारत सरकार और राज्य सरकारों की योजनाओं को खोजने का आधिकारिक एआई प्लेटफॉर्म है. आप हिंदी, गुजराती या अंग्रेजी में किसी भी योजना के बारे में पूछ सकते हैं.";',
'            } else {',
'                reply = "🤖 **About JanSahay AI:**\\n\\n" +',
'                        "JanSahay AI is an intelligent government scheme discovery platform covering 4,700+ Central and State Government schemes across India.\\n\\n" +',
'                        "✨ **How I Can Help You:**\\n" +',
'                        "- Recommend schemes tailored to your personal profile\\n" +',
'                        "- Explain benefits, eligibility criteria, and required documents\\n" +',
'                        "- Guide you to official government application portals\\n\\n" +',
'                        "You can speak or chat with me in English, Hindi, or Gujarati!";',
'                spokenText = "JanSahay AI helps Indian citizens discover relevant Central and State government schemes, check eligibility, and find official application portals. You can ask me in English, Hindi, or Gujarati.";',
'            }',
'',
'            return respond(reply, spokenText, \'idle\');',
'        }',
'',
'        // 12. Free-text search across all schemes using Intelligence Matcher',
'        const searchResults = matchSchemesWithIntelligence({',
'            query: userText,',
'            profile: session.profile,',
'            limit: 4,',
'            offset: 0',
'        });',
'',
'        if (searchResults.length > 0) {',
'            session.lastSchemes = searchResults;',
'            session.activeScheme = searchResults[0];',
'',
'            let reply = \'\';',
'            let spokenText = \'\';',
'',
'            if (lang === \'gu\') {',
'                reply = "🔍 **\\"" + userText + "\\"** સંબંધિત ઉપલબ્ધ યોજનાઓ:\\n\\n" +',
'                        searchResults.map((s, idx) => (idx + 1) + ". **" + s.title + "**\\n- **લાભ:** " + s.benefits + "\\n- 🔗 [સત્તાવાર પોર્ટલ](" + (s.applyLink || "#") + ")").join(\'\\n\\n\') +',
'                        "\\n\\nઆપેલી માહિતી મુજબ, તમે પાત્ર હોઈ શકો છો. ચોક્કસ યોજનાની સંપૂર્ણ વિગતો જાણવા માટે તેનું નામ કહો.";',
'                spokenText = "તમારા માટે સંબંધિત યોજનાઓ મળી છે, જેમાં " + searchResults.map(s => s.title).join(\', \') + " શામેલ છે.";',
'            } else if (lang === \'hi\') {',
'                reply = "🔍 **\\"" + userText + "\\"** से संबंधित उपलब्ध योजनाएं:\\n\\n" +',
'                        searchResults.map((s, idx) => (idx + 1) + ". **" + s.title + "**\\n- **लाभ:** " + s.benefits + "\\n- 🔗 [आधिकारिक पोर्टल](" + (s.applyLink || "#") + ")").join(\'\\n\\n\') +',
'                        "\\n\\nदी गई जानकारी के आधार पर, आप पात्र हो सकते हैं। किसी विशिष्ट योजना की पूरी जानकारी के लिए उसका नाम बताएं।";',
'                spokenText = "आपके लिए संबंधित योजनाएं मिली हैं, जैसे " + searchResults.map(s => s.title).join(\', \') + ".";',
'            } else {',
'                reply = "🔍 Government schemes matching **\\"" + userText + "\\"**:\\n\\n" +',
'                        searchResults.map((s, idx) => (idx + 1) + ". **" + s.title + "**\\n- **Benefits:** " + s.benefits + "\\n- 🔗 [Official Portal](" + (s.applyLink || "#") + ")").join(\'\\n\\n\') +',
'                        "\\n\\nBased on the information provided, you may be eligible. Mention any scheme to hear full application details!";',
'                spokenText = "I found matching schemes including " + searchResults.map(s => s.title).join(\', \') + ". Mention any scheme to hear full details.";',
'            }',
'',
'            return respond(reply, spokenText, \'matched\', searchResults);',
'        }',
'',
'        // 13. External Gemini AI (if API key available)',
'        const systemPrompt = "You are JanSahay AI Assistant, the official AI assistant for the JanSahay AI government scheme discovery platform.\\nYou support English, Hindi and Gujarati.\\nBe friendly, patient, respectful and simple.\\nAsk only the information necessary for the user\'s request.\\nNever repeat the exact same answers. Never invent fake schemes.\\nNever guarantee eligibility. Always state: \\"Based on the information provided, you may be eligible.\\"";',
'',
'        const geminiReply = await callGeminiIfAvailable(userText, systemPrompt, session.history, schemes.slice(0, 15));',
'        if (geminiReply) {',
'            const spokenGemini = createSpokenText(geminiReply);',
'            return respond(geminiReply, spokenGemini, \'idle\');',
'        }',
'',
'        // 14. Conversational Guidance Fallback',
'        let fallbackReply = \'\';',
'        let fallbackSpoken = \'\';',
'',
'        if (lang === \'gu\') {',
'            fallbackReply = "નમસ્તે! 🙏 હું તમને સરકારી યોજનાઓ શોધવામાં મદદ કરી શકું છું.\\n\\nતમારા માટે યોગ્ય યોજના શોધવા માટે, કૃપા કરીને જણાવો:\\n- **તમારો વ્યવસાય શું છે?** (દા.ત. ખેડૂત, વિદ્યાર્થી, વેપારી, મહિલા)\\n- અથવા પૂછો: *\\"ખેડૂતો માટે કઈ યોજના છે?\\"* કે *\\"વિદ્યાર્થીઓ માટે સ્કોલરશિપ કઈ છે?\\"*";',
'            fallbackSpoken = "નમસ્તે! હું તમને સરકારી યોજનાઓ શોધવામાં મદદ કરી શકું છું. તમે ખેતી, સ્કોલરશિપ, અથવા બિઝનેસ લોન વિશે પૂછી શકો છો.";',
'        } else if (lang === \'hi\') {',
'            fallbackReply = "नमस्ते! 🙏 मैं आपको केंद्र और राज्य सरकार की कल्याणकारी योजनाओं से जोड़ सकता हूँ।\\n\\nकृपया अपनी श्रेणी बताएं:\\n- **आप क्या करते हैं?** (जैसे: किसान, छात्र, व्यवसायी, या महिला कल्याण)\\n- या पूछें: *\\"छात्रवृत्ति कैसे मिलेगी?\\"* या *\\"मुद्रा लोन की जानकारी दें\\"*";',
'            fallbackSpoken = "नमस्ते! मैं आपको सरकारी योजनाओं की सही जानकारी दे सकता हूँ. आप किसान, छात्रवृत्ति, या व्यवसाय ऋण के बारे में पूछ सकते हैं.";',
'        } else {',
'            fallbackReply = "Namaste! 🙏 I can help you discover 4,700+ Central and State Government schemes tailored to your needs.\\n\\nTo find the best schemes for you:\\n- **What is your occupation or need?** (e.g. Farmer, Student, Business/Startup, Healthcare)\\n- Or try asking: *\\"Are there schemes for farmers in Gujarat?\\"* or *\\"How do I apply for a scholarship?\\"*";',
'            fallbackSpoken = "Namaste! I can help you discover Central and State government schemes. You can tell me your occupation or ask about scholarships, farmer schemes, or healthcare.";',
'        }',
'',
'        return respond(fallbackReply, fallbackSpoken, \'idle\');',
'',
'    } catch (error) {',
'        console.error(\'[VoiceController Error]:\', error);',
'        return res.status(500).json({',
'            success: false,',
'            error: \'Internal Server Error in JanSahay Voice Assistant\',',
'            message: \'An error occurred while processing your voice request. Please try again.\'',
'        });',
'    }',
'};',
'',
'// ── Reset Session Handler ─────────────────────────────────────',
'exports.resetSession = (req, res) => {',
'    const { sessionId } = req.body;',
'    if (sessionId && sessions.has(sessionId)) {',
'        sessions.delete(sessionId);',
'    }',
'    res.json({',
'        success: true,',
'        message: \'Session reset successfully\'',
'    });',
'};',
'',
'// ── Status Handler ────────────────────────────────────────────',
'exports.status = (req, res) => {',
'    res.json({',
'        success: true,',
'        service: \'JanSahay Multilingual Voice AI Assistant\',',
'        languages: [\'en\', \'hi\', \'gu\'],',
'        totalSchemesLoaded: schemes.length,',
'        activeSessions: sessions.size,',
'        hasGeminiApiKey: Boolean(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY)',
'    });',
'};',
'',
'// ── Health Diagnostic Handler (Section 18 Spec) ───────────────',
'exports.health = (req, res) => {',
'    const hasKey = Boolean(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY);',
'    res.json({',
'        microphone: "browser-controlled",',
'        stt: "healthy",',
'        backend: "healthy",',
'        llm: hasKey ? "healthy" : "unavailable",',
'        tts: "healthy"',
'    });',
'};'
].join('\n');

fs.writeFileSync(targetPath, part1 + '\n' + part2, 'utf8');
console.log('Successfully written updated voiceController.js!');
